/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Operator = IDL.Variant({
  'vi' : IDL.Null,
  'jio' : IDL.Null,
  'bsnl' : IDL.Null,
  'airtel' : IDL.Null,
  'tataSky' : IDL.Null,
  'dishTV' : IDL.Null,
});
export const PlanType = IDL.Variant({ 'dth' : IDL.Null, 'mobile' : IDL.Null });
export const CreatePlanArgs = IDL.Record({
  'validity' : IDL.Nat,
  'operator' : Operator,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
  'planType' : PlanType,
});
export const PlanId = IDL.Nat;
export const PlanView = IDL.Record({
  'id' : PlanId,
  'validity' : IDL.Nat,
  'operator' : Operator,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Nat,
  'planType' : PlanType,
});
export const TransactionId = IDL.Nat;
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'planId' : PlanId,
  'userId' : UserId,
  'operator' : Operator,
  'targetNumber' : IDL.Text,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
});
export const TxStatus = IDL.Variant({
  'pending' : IDL.Null,
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const TxType = IDL.Variant({
  'topUp' : IDL.Null,
  'bill' : IDL.Null,
  'deposit' : IDL.Null,
  'recharge' : IDL.Null,
  'transfer' : IDL.Null,
});
export const TxFilter = IDL.Record({
  'status' : IDL.Opt(TxStatus),
  'dateTo' : IDL.Opt(Timestamp),
  'operator' : IDL.Opt(Operator),
  'txType' : IDL.Opt(TxType),
  'dateFrom' : IDL.Opt(Timestamp),
});
export const BillCategory = IDL.Variant({
  'gas' : IDL.Null,
  'internet' : IDL.Null,
  'electricity' : IDL.Null,
  'water' : IDL.Null,
});
export const TxExtra = IDL.Variant({
  'topUp' : IDL.Record({}),
  'bill' : IDL.Record({ 'billerId' : IDL.Text, 'category' : BillCategory }),
  'deposit' : IDL.Record({
    'durationDays' : IDL.Nat,
    'interestRate' : IDL.Nat,
  }),
  'recharge' : IDL.Record({
    'planId' : IDL.Nat,
    'operator' : Operator,
    'targetNumber' : IDL.Text,
  }),
  'transfer' : IDL.Record({ 'note' : IDL.Text, 'recipientId' : UserId }),
});
export const TxRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : TxStatus,
  'userId' : UserId,
  'extra' : TxExtra,
  'timestamp' : Timestamp,
  'txType' : TxType,
  'amount' : IDL.Nat,
});
export const OperatorRevenue = IDL.Record({
  'operator' : Operator,
  'totalCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const Analytics = IDL.Record({
  'totalCount' : IDL.Nat,
  'byOperator' : IDL.Vec(OperatorRevenue),
  'totalRevenue' : IDL.Nat,
});
export const AppSettings = IDL.Record({
  'enableMobileRecharge' : IDL.Bool,
  'enableDthRecharge' : IDL.Bool,
  'appDisplayName' : IDL.Text,
  'commissionRateBps' : IDL.Nat,
  'enableDigitalDeposit' : IDL.Bool,
  'enableBillPayment' : IDL.Bool,
  'enableMoneyTransfer' : IDL.Bool,
});
export const UserProfileView = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'isAdmin' : IDL.Bool,
  'walletBalance' : IDL.Int,
});
export const UpdatePlanArgs = IDL.Record({
  'id' : PlanId,
  'validity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const AppSettingsUpdate = IDL.Record({
  'enableMobileRecharge' : IDL.Opt(IDL.Bool),
  'enableDthRecharge' : IDL.Opt(IDL.Bool),
  'appDisplayName' : IDL.Opt(IDL.Text),
  'commissionRateBps' : IDL.Opt(IDL.Nat),
  'enableDigitalDeposit' : IDL.Opt(IDL.Bool),
  'enableBillPayment' : IDL.Opt(IDL.Bool),
  'enableMoneyTransfer' : IDL.Opt(IDL.Bool),
});
export const DepositId = IDL.Nat;
export const DepositStatus = IDL.Variant({
  'active' : IDL.Null,
  'matured' : IDL.Null,
  'withdrawn' : IDL.Null,
});
export const DepositRecord = IDL.Record({
  'id' : DepositId,
  'durationDays' : IDL.Nat,
  'maturedAt' : IDL.Opt(Timestamp),
  'startTime' : Timestamp,
  'status' : DepositStatus,
  'principal' : IDL.Nat,
  'maturityTime' : Timestamp,
  'userId' : UserId,
  'interestRate' : IDL.Nat,
  'interestEarned' : IDL.Nat,
});
export const DepositResult = IDL.Variant({
  'ok' : DepositRecord,
  'err' : IDL.Text,
  'insufficientBalance' : IDL.Null,
  'userNotFound' : IDL.Null,
  'invalidDuration' : IDL.Null,
});
export const BillId = IDL.Nat;
export const BillStatus = IDL.Variant({
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const BillRecord = IDL.Record({
  'id' : BillId,
  'status' : BillStatus,
  'userId' : UserId,
  'billerId' : IDL.Text,
  'timestamp' : Timestamp,
  'category' : BillCategory,
  'amount' : IDL.Nat,
});
export const PublicSettings = IDL.Record({
  'enableMobileRecharge' : IDL.Bool,
  'enableDthRecharge' : IDL.Bool,
  'appDisplayName' : IDL.Text,
  'enableDigitalDeposit' : IDL.Bool,
  'enableBillPayment' : IDL.Bool,
  'enableMoneyTransfer' : IDL.Bool,
});
export const TransferId = IDL.Nat;
export const TransferStatus = IDL.Variant({
  'success' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransferRecord = IDL.Record({
  'id' : TransferId,
  'status' : TransferStatus,
  'note' : IDL.Text,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
  'recipientId' : UserId,
  'senderId' : UserId,
});
export const InitiateRechargeArgs = IDL.Record({
  'planId' : PlanId,
  'targetNumber' : IDL.Text,
});
export const RechargeResult = IDL.Variant({
  'ok' : Transaction,
  'err' : IDL.Text,
  'insufficientBalance' : IDL.Null,
  'planNotFound' : IDL.Null,
  'planInactive' : IDL.Null,
});
export const MatureResult = IDL.Variant({
  'ok' : DepositRecord,
  'err' : IDL.Text,
  'alreadyProcessed' : IDL.Null,
  'notYetMatured' : IDL.Null,
  'depositNotFound' : IDL.Null,
});
export const BillPayResult = IDL.Variant({
  'ok' : BillRecord,
  'err' : IDL.Text,
  'insufficientBalance' : IDL.Null,
  'userNotFound' : IDL.Null,
});
export const TopUpResult = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
export const TransferResult = IDL.Variant({
  'ok' : TransferRecord,
  'err' : IDL.Text,
  'insufficientBalance' : IDL.Null,
  'recipientNotFound' : IDL.Null,
  'senderNotFound' : IDL.Null,
});

export const idlService = IDL.Service({
  'adminCreatePlan' : IDL.Func([CreatePlanArgs], [PlanView], []),
  'adminGetAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'adminGetAllTransactionsV2' : IDL.Func(
      [TxFilter],
      [IDL.Vec(TxRecord)],
      ['query'],
    ),
  'adminGetAnalytics' : IDL.Func([], [Analytics], ['query']),
  'adminGetSettings' : IDL.Func([], [AppSettings], ['query']),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
  'adminSetRole' : IDL.Func([UserId, IDL.Bool], [IDL.Bool], []),
  'adminTogglePlan' : IDL.Func([PlanId], [IDL.Opt(PlanView)], []),
  'adminUpdatePlan' : IDL.Func([UpdatePlanArgs], [IDL.Opt(PlanView)], []),
  'adminUpdateSettings' : IDL.Func([AppSettingsUpdate], [], []),
  'createDeposit' : IDL.Func([IDL.Nat, IDL.Nat], [DepositResult], []),
  'getActivePlans' : IDL.Func(
      [IDL.Opt(PlanType)],
      [IDL.Vec(PlanView)],
      ['query'],
    ),
  'getBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getMyBillPayments' : IDL.Func([], [IDL.Vec(BillRecord)], ['query']),
  'getMyDeposits' : IDL.Func([], [IDL.Vec(DepositRecord)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getPlan' : IDL.Func([PlanId], [IDL.Opt(PlanView)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getPublicSettings' : IDL.Func([], [PublicSettings], ['query']),
  'getTransferHistory' : IDL.Func([], [IDL.Vec(TransferRecord)], ['query']),
  'initiateRecharge' : IDL.Func([InitiateRechargeArgs], [RechargeResult], []),
  'matureDeposit' : IDL.Func([IDL.Nat], [MatureResult], []),
  'payBill' : IDL.Func([BillCategory, IDL.Text, IDL.Nat], [BillPayResult], []),
  'register' : IDL.Func([], [UserProfileView], []),
  'topUpWallet' : IDL.Func([IDL.Nat], [TopUpResult], []),
  'transferFunds' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Text],
      [TransferResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Operator = IDL.Variant({
    'vi' : IDL.Null,
    'jio' : IDL.Null,
    'bsnl' : IDL.Null,
    'airtel' : IDL.Null,
    'tataSky' : IDL.Null,
    'dishTV' : IDL.Null,
  });
  const PlanType = IDL.Variant({ 'dth' : IDL.Null, 'mobile' : IDL.Null });
  const CreatePlanArgs = IDL.Record({
    'validity' : IDL.Nat,
    'operator' : Operator,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
    'planType' : PlanType,
  });
  const PlanId = IDL.Nat;
  const PlanView = IDL.Record({
    'id' : PlanId,
    'validity' : IDL.Nat,
    'operator' : Operator,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Nat,
    'planType' : PlanType,
  });
  const TransactionId = IDL.Nat;
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'planId' : PlanId,
    'userId' : UserId,
    'operator' : Operator,
    'targetNumber' : IDL.Text,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
  });
  const TxStatus = IDL.Variant({
    'pending' : IDL.Null,
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TxType = IDL.Variant({
    'topUp' : IDL.Null,
    'bill' : IDL.Null,
    'deposit' : IDL.Null,
    'recharge' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const TxFilter = IDL.Record({
    'status' : IDL.Opt(TxStatus),
    'dateTo' : IDL.Opt(Timestamp),
    'operator' : IDL.Opt(Operator),
    'txType' : IDL.Opt(TxType),
    'dateFrom' : IDL.Opt(Timestamp),
  });
  const BillCategory = IDL.Variant({
    'gas' : IDL.Null,
    'internet' : IDL.Null,
    'electricity' : IDL.Null,
    'water' : IDL.Null,
  });
  const TxExtra = IDL.Variant({
    'topUp' : IDL.Record({}),
    'bill' : IDL.Record({ 'billerId' : IDL.Text, 'category' : BillCategory }),
    'deposit' : IDL.Record({
      'durationDays' : IDL.Nat,
      'interestRate' : IDL.Nat,
    }),
    'recharge' : IDL.Record({
      'planId' : IDL.Nat,
      'operator' : Operator,
      'targetNumber' : IDL.Text,
    }),
    'transfer' : IDL.Record({ 'note' : IDL.Text, 'recipientId' : UserId }),
  });
  const TxRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : TxStatus,
    'userId' : UserId,
    'extra' : TxExtra,
    'timestamp' : Timestamp,
    'txType' : TxType,
    'amount' : IDL.Nat,
  });
  const OperatorRevenue = IDL.Record({
    'operator' : Operator,
    'totalCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const Analytics = IDL.Record({
    'totalCount' : IDL.Nat,
    'byOperator' : IDL.Vec(OperatorRevenue),
    'totalRevenue' : IDL.Nat,
  });
  const AppSettings = IDL.Record({
    'enableMobileRecharge' : IDL.Bool,
    'enableDthRecharge' : IDL.Bool,
    'appDisplayName' : IDL.Text,
    'commissionRateBps' : IDL.Nat,
    'enableDigitalDeposit' : IDL.Bool,
    'enableBillPayment' : IDL.Bool,
    'enableMoneyTransfer' : IDL.Bool,
  });
  const UserProfileView = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'isAdmin' : IDL.Bool,
    'walletBalance' : IDL.Int,
  });
  const UpdatePlanArgs = IDL.Record({
    'id' : PlanId,
    'validity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const AppSettingsUpdate = IDL.Record({
    'enableMobileRecharge' : IDL.Opt(IDL.Bool),
    'enableDthRecharge' : IDL.Opt(IDL.Bool),
    'appDisplayName' : IDL.Opt(IDL.Text),
    'commissionRateBps' : IDL.Opt(IDL.Nat),
    'enableDigitalDeposit' : IDL.Opt(IDL.Bool),
    'enableBillPayment' : IDL.Opt(IDL.Bool),
    'enableMoneyTransfer' : IDL.Opt(IDL.Bool),
  });
  const DepositId = IDL.Nat;
  const DepositStatus = IDL.Variant({
    'active' : IDL.Null,
    'matured' : IDL.Null,
    'withdrawn' : IDL.Null,
  });
  const DepositRecord = IDL.Record({
    'id' : DepositId,
    'durationDays' : IDL.Nat,
    'maturedAt' : IDL.Opt(Timestamp),
    'startTime' : Timestamp,
    'status' : DepositStatus,
    'principal' : IDL.Nat,
    'maturityTime' : Timestamp,
    'userId' : UserId,
    'interestRate' : IDL.Nat,
    'interestEarned' : IDL.Nat,
  });
  const DepositResult = IDL.Variant({
    'ok' : DepositRecord,
    'err' : IDL.Text,
    'insufficientBalance' : IDL.Null,
    'userNotFound' : IDL.Null,
    'invalidDuration' : IDL.Null,
  });
  const BillId = IDL.Nat;
  const BillStatus = IDL.Variant({ 'success' : IDL.Null, 'failed' : IDL.Null });
  const BillRecord = IDL.Record({
    'id' : BillId,
    'status' : BillStatus,
    'userId' : UserId,
    'billerId' : IDL.Text,
    'timestamp' : Timestamp,
    'category' : BillCategory,
    'amount' : IDL.Nat,
  });
  const PublicSettings = IDL.Record({
    'enableMobileRecharge' : IDL.Bool,
    'enableDthRecharge' : IDL.Bool,
    'appDisplayName' : IDL.Text,
    'enableDigitalDeposit' : IDL.Bool,
    'enableBillPayment' : IDL.Bool,
    'enableMoneyTransfer' : IDL.Bool,
  });
  const TransferId = IDL.Nat;
  const TransferStatus = IDL.Variant({
    'success' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransferRecord = IDL.Record({
    'id' : TransferId,
    'status' : TransferStatus,
    'note' : IDL.Text,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
    'recipientId' : UserId,
    'senderId' : UserId,
  });
  const InitiateRechargeArgs = IDL.Record({
    'planId' : PlanId,
    'targetNumber' : IDL.Text,
  });
  const RechargeResult = IDL.Variant({
    'ok' : Transaction,
    'err' : IDL.Text,
    'insufficientBalance' : IDL.Null,
    'planNotFound' : IDL.Null,
    'planInactive' : IDL.Null,
  });
  const MatureResult = IDL.Variant({
    'ok' : DepositRecord,
    'err' : IDL.Text,
    'alreadyProcessed' : IDL.Null,
    'notYetMatured' : IDL.Null,
    'depositNotFound' : IDL.Null,
  });
  const BillPayResult = IDL.Variant({
    'ok' : BillRecord,
    'err' : IDL.Text,
    'insufficientBalance' : IDL.Null,
    'userNotFound' : IDL.Null,
  });
  const TopUpResult = IDL.Variant({ 'ok' : IDL.Int, 'err' : IDL.Text });
  const TransferResult = IDL.Variant({
    'ok' : TransferRecord,
    'err' : IDL.Text,
    'insufficientBalance' : IDL.Null,
    'recipientNotFound' : IDL.Null,
    'senderNotFound' : IDL.Null,
  });
  
  return IDL.Service({
    'adminCreatePlan' : IDL.Func([CreatePlanArgs], [PlanView], []),
    'adminGetAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'adminGetAllTransactionsV2' : IDL.Func(
        [TxFilter],
        [IDL.Vec(TxRecord)],
        ['query'],
      ),
    'adminGetAnalytics' : IDL.Func([], [Analytics], ['query']),
    'adminGetSettings' : IDL.Func([], [AppSettings], ['query']),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
    'adminSetRole' : IDL.Func([UserId, IDL.Bool], [IDL.Bool], []),
    'adminTogglePlan' : IDL.Func([PlanId], [IDL.Opt(PlanView)], []),
    'adminUpdatePlan' : IDL.Func([UpdatePlanArgs], [IDL.Opt(PlanView)], []),
    'adminUpdateSettings' : IDL.Func([AppSettingsUpdate], [], []),
    'createDeposit' : IDL.Func([IDL.Nat, IDL.Nat], [DepositResult], []),
    'getActivePlans' : IDL.Func(
        [IDL.Opt(PlanType)],
        [IDL.Vec(PlanView)],
        ['query'],
      ),
    'getBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getMyBillPayments' : IDL.Func([], [IDL.Vec(BillRecord)], ['query']),
    'getMyDeposits' : IDL.Func([], [IDL.Vec(DepositRecord)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getPlan' : IDL.Func([PlanId], [IDL.Opt(PlanView)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
    'getPublicSettings' : IDL.Func([], [PublicSettings], ['query']),
    'getTransferHistory' : IDL.Func([], [IDL.Vec(TransferRecord)], ['query']),
    'initiateRecharge' : IDL.Func([InitiateRechargeArgs], [RechargeResult], []),
    'matureDeposit' : IDL.Func([IDL.Nat], [MatureResult], []),
    'payBill' : IDL.Func(
        [BillCategory, IDL.Text, IDL.Nat],
        [BillPayResult],
        [],
      ),
    'register' : IDL.Func([], [UserProfileView], []),
    'topUpWallet' : IDL.Func([IDL.Nat], [TopUpResult], []),
    'transferFunds' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Text],
        [TransferResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };