/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalCount' : bigint,
  'byOperator' : Array<OperatorRevenue>,
  'totalRevenue' : bigint,
}
export interface AppSettings {
  'enableMobileRecharge' : boolean,
  'enableDthRecharge' : boolean,
  'appDisplayName' : string,
  'commissionRateBps' : bigint,
  'enableDigitalDeposit' : boolean,
  'enableBillPayment' : boolean,
  'enableMoneyTransfer' : boolean,
}
export interface AppSettingsUpdate {
  'enableMobileRecharge' : [] | [boolean],
  'enableDthRecharge' : [] | [boolean],
  'appDisplayName' : [] | [string],
  'commissionRateBps' : [] | [bigint],
  'enableDigitalDeposit' : [] | [boolean],
  'enableBillPayment' : [] | [boolean],
  'enableMoneyTransfer' : [] | [boolean],
}
export type BillCategory = { 'gas' : null } |
  { 'internet' : null } |
  { 'electricity' : null } |
  { 'water' : null };
export type BillId = bigint;
export type BillPayResult = { 'ok' : BillRecord } |
  { 'err' : string } |
  { 'insufficientBalance' : null } |
  { 'userNotFound' : null };
export interface BillRecord {
  'id' : BillId,
  'status' : BillStatus,
  'userId' : UserId,
  'billerId' : string,
  'timestamp' : Timestamp,
  'category' : BillCategory,
  'amount' : bigint,
}
export type BillStatus = { 'success' : null } |
  { 'failed' : null };
export interface CreatePlanArgs {
  'validity' : bigint,
  'operator' : Operator,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'planType' : PlanType,
}
export type DepositId = bigint;
export interface DepositRecord {
  'id' : DepositId,
  'durationDays' : bigint,
  'maturedAt' : [] | [Timestamp],
  'startTime' : Timestamp,
  'status' : DepositStatus,
  'principal' : bigint,
  'maturityTime' : Timestamp,
  'userId' : UserId,
  'interestRate' : bigint,
  'interestEarned' : bigint,
}
export type DepositResult = { 'ok' : DepositRecord } |
  { 'err' : string } |
  { 'insufficientBalance' : null } |
  { 'userNotFound' : null } |
  { 'invalidDuration' : null };
export type DepositStatus = { 'active' : null } |
  { 'matured' : null } |
  { 'withdrawn' : null };
export interface InitiateRechargeArgs {
  'planId' : PlanId,
  'targetNumber' : string,
}
export type MatureResult = { 'ok' : DepositRecord } |
  { 'err' : string } |
  { 'alreadyProcessed' : null } |
  { 'notYetMatured' : null } |
  { 'depositNotFound' : null };
export type Operator = { 'vi' : null } |
  { 'jio' : null } |
  { 'bsnl' : null } |
  { 'airtel' : null } |
  { 'tataSky' : null } |
  { 'dishTV' : null };
export interface OperatorRevenue {
  'operator' : Operator,
  'totalCount' : bigint,
  'totalRevenue' : bigint,
}
export type PlanId = bigint;
export type PlanType = { 'dth' : null } |
  { 'mobile' : null };
export interface PlanView {
  'id' : PlanId,
  'validity' : bigint,
  'operator' : Operator,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'price' : bigint,
  'planType' : PlanType,
}
export interface PublicSettings {
  'enableMobileRecharge' : boolean,
  'enableDthRecharge' : boolean,
  'appDisplayName' : string,
  'enableDigitalDeposit' : boolean,
  'enableBillPayment' : boolean,
  'enableMoneyTransfer' : boolean,
}
export type RechargeResult = { 'ok' : Transaction } |
  { 'err' : string } |
  { 'insufficientBalance' : null } |
  { 'planNotFound' : null } |
  { 'planInactive' : null };
export type Timestamp = bigint;
export type TopUpResult = { 'ok' : bigint } |
  { 'err' : string };
export interface Transaction {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'planId' : PlanId,
  'userId' : UserId,
  'operator' : Operator,
  'targetNumber' : string,
  'timestamp' : Timestamp,
  'amount' : bigint,
}
export type TransactionId = bigint;
export type TransactionStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export type TransferId = bigint;
export interface TransferRecord {
  'id' : TransferId,
  'status' : TransferStatus,
  'note' : string,
  'timestamp' : Timestamp,
  'amount' : bigint,
  'recipientId' : UserId,
  'senderId' : UserId,
}
export type TransferResult = { 'ok' : TransferRecord } |
  { 'err' : string } |
  { 'insufficientBalance' : null } |
  { 'recipientNotFound' : null } |
  { 'senderNotFound' : null };
export type TransferStatus = { 'success' : null } |
  { 'failed' : null };
export type TxExtra = { 'topUp' : {} } |
  { 'bill' : { 'billerId' : string, 'category' : BillCategory } } |
  { 'deposit' : { 'durationDays' : bigint, 'interestRate' : bigint } } |
  {
    'recharge' : {
      'planId' : bigint,
      'operator' : Operator,
      'targetNumber' : string,
    }
  } |
  { 'transfer' : { 'note' : string, 'recipientId' : UserId } };
export interface TxFilter {
  'status' : [] | [TxStatus],
  'dateTo' : [] | [Timestamp],
  'operator' : [] | [Operator],
  'txType' : [] | [TxType],
  'dateFrom' : [] | [Timestamp],
}
export interface TxRecord {
  'id' : bigint,
  'status' : TxStatus,
  'userId' : UserId,
  'extra' : TxExtra,
  'timestamp' : Timestamp,
  'txType' : TxType,
  'amount' : bigint,
}
export type TxStatus = { 'pending' : null } |
  { 'success' : null } |
  { 'failed' : null };
export type TxType = { 'topUp' : null } |
  { 'bill' : null } |
  { 'deposit' : null } |
  { 'recharge' : null } |
  { 'transfer' : null };
export interface UpdatePlanArgs {
  'id' : PlanId,
  'validity' : bigint,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type UserId = Principal;
export interface UserProfileView {
  'id' : UserId,
  'createdAt' : Timestamp,
  'isAdmin' : boolean,
  'walletBalance' : bigint,
}
export interface _SERVICE {
  'adminCreatePlan' : ActorMethod<[CreatePlanArgs], PlanView>,
  'adminGetAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'adminGetAllTransactionsV2' : ActorMethod<[TxFilter], Array<TxRecord>>,
  'adminGetAnalytics' : ActorMethod<[], Analytics>,
  'adminGetSettings' : ActorMethod<[], AppSettings>,
  'adminListUsers' : ActorMethod<[], Array<UserProfileView>>,
  'adminSetRole' : ActorMethod<[UserId, boolean], boolean>,
  'adminTogglePlan' : ActorMethod<[PlanId], [] | [PlanView]>,
  'adminUpdatePlan' : ActorMethod<[UpdatePlanArgs], [] | [PlanView]>,
  'adminUpdateSettings' : ActorMethod<[AppSettingsUpdate], undefined>,
  'createDeposit' : ActorMethod<[bigint, bigint], DepositResult>,
  'getActivePlans' : ActorMethod<[[] | [PlanType]], Array<PlanView>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getMyBillPayments' : ActorMethod<[], Array<BillRecord>>,
  'getMyDeposits' : ActorMethod<[], Array<DepositRecord>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getPlan' : ActorMethod<[PlanId], [] | [PlanView]>,
  'getProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getPublicSettings' : ActorMethod<[], PublicSettings>,
  'getTransferHistory' : ActorMethod<[], Array<TransferRecord>>,
  'initiateRecharge' : ActorMethod<[InitiateRechargeArgs], RechargeResult>,
  'matureDeposit' : ActorMethod<[bigint], MatureResult>,
  'payBill' : ActorMethod<[BillCategory, string, bigint], BillPayResult>,
  'register' : ActorMethod<[], UserProfileView>,
  'topUpWallet' : ActorMethod<[bigint], TopUpResult>,
  'transferFunds' : ActorMethod<[Principal, bigint, string], TransferResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];