/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface BillRecord {
    id: BillId;
    status: BillStatus;
    userId: UserId;
    billerId: string;
    timestamp: Timestamp;
    category: BillCategory;
    amount: bigint;
}
export type BillPayResult = {
    __kind__: "ok";
    ok: BillRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
};
export interface PlanView {
    id: PlanId;
    validity: bigint;
    operator: Operator;
    name: string;
    description: string;
    isActive: boolean;
    price: bigint;
    planType: PlanType;
}
export interface OperatorRevenue {
    operator: Operator;
    totalCount: bigint;
    totalRevenue: bigint;
}
export type DepositResult = {
    __kind__: "ok";
    ok: DepositRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
} | {
    __kind__: "invalidDuration";
    invalidDuration: null;
};
export interface TransferRecord {
    id: TransferId;
    status: TransferStatus;
    note: string;
    timestamp: Timestamp;
    amount: bigint;
    recipientId: UserId;
    senderId: UserId;
}
export type BillId = bigint;
export interface Transaction {
    id: TransactionId;
    status: TransactionStatus;
    planId: PlanId;
    userId: UserId;
    operator: Operator;
    targetNumber: string;
    timestamp: Timestamp;
    amount: bigint;
}
export type RechargeResult = {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "planNotFound";
    planNotFound: null;
} | {
    __kind__: "planInactive";
    planInactive: null;
};
export type TopUpResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type TransactionId = bigint;
export interface InitiateRechargeArgs {
    planId: PlanId;
    targetNumber: string;
}
export interface DepositRecord {
    id: DepositId;
    durationDays: bigint;
    maturedAt?: Timestamp;
    startTime: Timestamp;
    status: DepositStatus;
    principal: bigint;
    maturityTime: Timestamp;
    userId: UserId;
    interestRate: bigint;
    interestEarned: bigint;
}
export type TransferResult = {
    __kind__: "ok";
    ok: TransferRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "recipientNotFound";
    recipientNotFound: null;
} | {
    __kind__: "senderNotFound";
    senderNotFound: null;
};
export interface Analytics {
    totalCount: bigint;
    byOperator: Array<OperatorRevenue>;
    totalRevenue: bigint;
}
export type PlanId = bigint;
export interface CreatePlanArgs {
    validity: bigint;
    operator: Operator;
    name: string;
    description: string;
    price: bigint;
    planType: PlanType;
}
export interface PublicSettings {
    enableMobileRecharge: boolean;
    enableDthRecharge: boolean;
    appDisplayName: string;
    enableDigitalDeposit: boolean;
    enableBillPayment: boolean;
    enableMoneyTransfer: boolean;
}
export interface UpdatePlanArgs {
    id: PlanId;
    validity: bigint;
    name: string;
    description: string;
    price: bigint;
}
export type TxExtra = {
    __kind__: "topUp";
    topUp: {
    };
} | {
    __kind__: "bill";
    bill: {
        billerId: string;
        category: BillCategory;
    };
} | {
    __kind__: "deposit";
    deposit: {
        durationDays: bigint;
        interestRate: bigint;
    };
} | {
    __kind__: "recharge";
    recharge: {
        planId: bigint;
        operator: Operator;
        targetNumber: string;
    };
} | {
    __kind__: "transfer";
    transfer: {
        note: string;
        recipientId: UserId;
    };
};
export interface AppSettingsUpdate {
    enableMobileRecharge?: boolean;
    enableDthRecharge?: boolean;
    appDisplayName?: string;
    commissionRateBps?: bigint;
    enableDigitalDeposit?: boolean;
    enableBillPayment?: boolean;
    enableMoneyTransfer?: boolean;
}
export interface AppSettings {
    enableMobileRecharge: boolean;
    enableDthRecharge: boolean;
    appDisplayName: string;
    commissionRateBps: bigint;
    enableDigitalDeposit: boolean;
    enableBillPayment: boolean;
    enableMoneyTransfer: boolean;
}
export type UserId = Principal;
export type TransferId = bigint;
export interface UserProfileView {
    id: UserId;
    createdAt: Timestamp;
    isAdmin: boolean;
    walletBalance: bigint;
}
export interface TxRecord {
    id: bigint;
    status: TxStatus;
    userId: UserId;
    extra: TxExtra;
    timestamp: Timestamp;
    txType: TxType;
    amount: bigint;
}
export interface TxFilter {
    status?: TxStatus;
    dateTo?: Timestamp;
    operator?: Operator;
    txType?: TxType;
    dateFrom?: Timestamp;
}
export type DepositId = bigint;
export type MatureResult = {
    __kind__: "ok";
    ok: DepositRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "alreadyProcessed";
    alreadyProcessed: null;
} | {
    __kind__: "notYetMatured";
    notYetMatured: null;
} | {
    __kind__: "depositNotFound";
    depositNotFound: null;
};
export enum BillCategory {
    gas = "gas",
    internet = "internet",
    electricity = "electricity",
    water = "water"
}
export enum BillStatus {
    success = "success",
    failed = "failed"
}
export enum DepositStatus {
    active = "active",
    matured = "matured",
    withdrawn = "withdrawn"
}
export enum Operator {
    vi = "vi",
    jio = "jio",
    bsnl = "bsnl",
    airtel = "airtel",
    tataSky = "tataSky",
    dishTV = "dishTV"
}
export enum PlanType {
    dth = "dth",
    mobile = "mobile"
}
export enum TransactionStatus {
    pending = "pending",
    success = "success",
    failed = "failed"
}
export enum TxType {
    topUp = "topUp",
    bill = "bill",
    deposit = "deposit",
    recharge = "recharge",
    transfer = "transfer"
}
export interface backendInterface {
    adminCreatePlan(args: CreatePlanArgs): Promise<PlanView>;
    adminGetAllTransactions(): Promise<Array<Transaction>>;
    adminGetAllTransactionsV2(filter: TxFilter): Promise<Array<TxRecord>>;
    adminGetAnalytics(): Promise<Analytics>;
    adminGetSettings(): Promise<AppSettings>;
    adminListUsers(): Promise<Array<UserProfileView>>;
    adminSetRole(target: UserId, isAdmin: boolean): Promise<boolean>;
    adminTogglePlan(id: PlanId): Promise<PlanView | null>;
    adminUpdatePlan(args: UpdatePlanArgs): Promise<PlanView | null>;
    adminUpdateSettings(update: AppSettingsUpdate): Promise<void>;
    createDeposit(amount: bigint, durationDays: bigint): Promise<DepositResult>;
    getActivePlans(planType: PlanType | null): Promise<Array<PlanView>>;
    getBalance(): Promise<bigint>;
    getMyBillPayments(): Promise<Array<BillRecord>>;
    getMyDeposits(): Promise<Array<DepositRecord>>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getPlan(id: PlanId): Promise<PlanView | null>;
    getProfile(): Promise<UserProfileView | null>;
    getPublicSettings(): Promise<PublicSettings>;
    getTransferHistory(): Promise<Array<TransferRecord>>;
    initiateRecharge(args: InitiateRechargeArgs): Promise<RechargeResult>;
    matureDeposit(depositId: bigint): Promise<MatureResult>;
    payBill(category: BillCategory, billerId: string, amount: bigint): Promise<BillPayResult>;
    register(): Promise<UserProfileView>;
    topUpWallet(amountPaisa: bigint): Promise<TopUpResult>;
    transferFunds(recipientPrincipal: Principal, amount: bigint, note: string): Promise<TransferResult>;
}
import type { Analytics as _Analytics, AppSettingsUpdate as _AppSettingsUpdate, BillCategory as _BillCategory, BillId as _BillId, BillPayResult as _BillPayResult, BillRecord as _BillRecord, BillStatus as _BillStatus, CreatePlanArgs as _CreatePlanArgs, DepositId as _DepositId, DepositRecord as _DepositRecord, DepositResult as _DepositResult, DepositStatus as _DepositStatus, MatureResult as _MatureResult, Operator as _Operator, OperatorRevenue as _OperatorRevenue, PlanId as _PlanId, PlanType as _PlanType, PlanView as _PlanView, RechargeResult as _RechargeResult, Timestamp as _Timestamp, TopUpResult as _TopUpResult, Transaction as _Transaction, TransactionId as _TransactionId, TransactionStatus as _TransactionStatus, TransferId as _TransferId, TransferRecord as _TransferRecord, TransferResult as _TransferResult, TransferStatus as _TransferStatus, TxExtra as _TxExtra, TxFilter as _TxFilter, TxRecord as _TxRecord, TxStatus as _TxStatus, TxType as _TxType, UserId as _UserId, UserProfileView as _UserProfileView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminCreatePlan(arg0: CreatePlanArgs): Promise<PlanView> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreatePlan(to_candid_CreatePlanArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PlanView_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreatePlan(to_candid_CreatePlanArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PlanView_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllTransactionsV2(arg0: TxFilter): Promise<Array<TxRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactionsV2(to_candid_TxFilter_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactionsV2(to_candid_TxFilter_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAnalytics();
                return from_candid_Analytics_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAnalytics();
            return from_candid_Analytics_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSettings();
            return result;
        }
    }
    async adminListUsers(): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers();
            return result;
        }
    }
    async adminSetRole(arg0: UserId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetRole(arg0, arg1);
            return result;
        }
    }
    async adminTogglePlan(arg0: PlanId): Promise<PlanView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminTogglePlan(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminTogglePlan(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdatePlan(arg0: UpdatePlanArgs): Promise<PlanView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdatePlan(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdatePlan(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateSettings(arg0: AppSettingsUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateSettings(to_candid_AppSettingsUpdate_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateSettings(to_candid_AppSettingsUpdate_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createDeposit(arg0: bigint, arg1: bigint): Promise<DepositResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeposit(arg0, arg1);
                return from_candid_DepositResult_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeposit(arg0, arg1);
            return from_candid_DepositResult_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivePlans(arg0: PlanType | null): Promise<Array<PlanView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivePlans(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivePlans(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getMyBillPayments(): Promise<Array<BillRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBillPayments();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBillPayments();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDeposits(): Promise<Array<DepositRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDeposits();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDeposits();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlan(arg0: PlanId): Promise<PlanView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlan(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlan(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicSettings(): Promise<PublicSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicSettings();
            return result;
        }
    }
    async getTransferHistory(): Promise<Array<TransferRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransferHistory();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransferHistory();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async initiateRecharge(arg0: InitiateRechargeArgs): Promise<RechargeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateRecharge(arg0);
                return from_candid_RechargeResult_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateRecharge(arg0);
            return from_candid_RechargeResult_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async matureDeposit(arg0: bigint): Promise<MatureResult> {
        if (this.processError) {
            try {
                const result = await this.actor.matureDeposit(arg0);
                return from_candid_MatureResult_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.matureDeposit(arg0);
            return from_candid_MatureResult_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async payBill(arg0: BillCategory, arg1: string, arg2: bigint): Promise<BillPayResult> {
        if (this.processError) {
            try {
                const result = await this.actor.payBill(to_candid_BillCategory_n68(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_BillPayResult_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payBill(to_candid_BillCategory_n68(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_BillPayResult_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.register();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register();
            return result;
        }
    }
    async topUpWallet(arg0: bigint): Promise<TopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.topUpWallet(arg0);
                return from_candid_TopUpResult_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.topUpWallet(arg0);
            return from_candid_TopUpResult_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferFunds(arg0: Principal, arg1: bigint, arg2: string): Promise<TransferResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferFunds(arg0, arg1, arg2);
                return from_candid_TransferResult_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferFunds(arg0, arg1, arg2);
            return from_candid_TransferResult_n74(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Analytics_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Analytics): Analytics {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_BillCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillCategory): BillCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_BillPayResult_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillPayResult): BillPayResult {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_BillRecord_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillRecord): BillRecord {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_BillStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BillStatus): BillStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_DepositRecord_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositRecord): DepositRecord {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_DepositResult_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositResult): DepositResult {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_DepositStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositStatus): DepositStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_MatureResult_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatureResult): MatureResult {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_OperatorRevenue_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OperatorRevenue): OperatorRevenue {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Operator_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Operator): Operator {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PlanType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanType): PlanType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PlanView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanView): PlanView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RechargeResult_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RechargeResult): RechargeResult {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_TopUpResult_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopUpResult): TopUpResult {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TransferRecord_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferRecord): TransferRecord {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_TransferResult_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferResult): TransferResult {
    return from_candid_variant_n75(_uploadFile, _downloadFile, value);
}
function from_candid_TransferStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferStatus): TransferStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_TxExtra_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxExtra): TxExtra {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TxRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxRecord): TxRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_TxStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxStatus): TxStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlanView]): PlanView | null {
    return value.length === 0 ? null : from_candid_PlanView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    status: _TransactionStatus;
    planId: _PlanId;
    userId: _UserId;
    operator: _Operator;
    targetNumber: string;
    timestamp: _Timestamp;
    amount: bigint;
}): {
    id: TransactionId;
    status: TransactionStatus;
    planId: PlanId;
    userId: UserId;
    operator: Operator;
    targetNumber: string;
    timestamp: Timestamp;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n16(_uploadFile, _downloadFile, value.status),
        planId: value.planId,
        userId: value.userId,
        operator: from_candid_Operator_n9(_uploadFile, _downloadFile, value.operator),
        targetNumber: value.targetNumber,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TxStatus;
    userId: _UserId;
    extra: _TxExtra;
    timestamp: _Timestamp;
    txType: _TxType;
    amount: bigint;
}): {
    id: bigint;
    status: TxStatus;
    userId: UserId;
    extra: TxExtra;
    timestamp: Timestamp;
    txType: TxType;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TxStatus_n27(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        extra: from_candid_TxExtra_n28(_uploadFile, _downloadFile, value.extra),
        timestamp: value.timestamp,
        txType: from_candid_TxType_n34(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    billerId: string;
    category: _BillCategory;
}): {
    billerId: string;
    category: BillCategory;
} {
    return {
        billerId: value.billerId,
        category: from_candid_BillCategory_n31(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    planId: bigint;
    operator: _Operator;
    targetNumber: string;
}): {
    planId: bigint;
    operator: Operator;
    targetNumber: string;
} {
    return {
        planId: value.planId,
        operator: from_candid_Operator_n9(_uploadFile, _downloadFile, value.operator),
        targetNumber: value.targetNumber
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    byOperator: Array<_OperatorRevenue>;
    totalRevenue: bigint;
}): {
    totalCount: bigint;
    byOperator: Array<OperatorRevenue>;
    totalRevenue: bigint;
} {
    return {
        totalCount: value.totalCount,
        byOperator: from_candid_vec_n38(_uploadFile, _downloadFile, value.byOperator),
        totalRevenue: value.totalRevenue
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    operator: _Operator;
    totalCount: bigint;
    totalRevenue: bigint;
}): {
    operator: Operator;
    totalCount: bigint;
    totalRevenue: bigint;
} {
    return {
        operator: from_candid_Operator_n9(_uploadFile, _downloadFile, value.operator),
        totalCount: value.totalCount,
        totalRevenue: value.totalRevenue
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DepositId;
    durationDays: bigint;
    maturedAt: [] | [_Timestamp];
    startTime: _Timestamp;
    status: _DepositStatus;
    principal: bigint;
    maturityTime: _Timestamp;
    userId: _UserId;
    interestRate: bigint;
    interestEarned: bigint;
}): {
    id: DepositId;
    durationDays: bigint;
    maturedAt?: Timestamp;
    startTime: Timestamp;
    status: DepositStatus;
    principal: bigint;
    maturityTime: Timestamp;
    userId: UserId;
    interestRate: bigint;
    interestEarned: bigint;
} {
    return {
        id: value.id,
        durationDays: value.durationDays,
        maturedAt: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.maturedAt)),
        startTime: value.startTime,
        status: from_candid_DepositStatus_n49(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        maturityTime: value.maturityTime,
        userId: value.userId,
        interestRate: value.interestRate,
        interestEarned: value.interestEarned
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BillId;
    status: _BillStatus;
    userId: _UserId;
    billerId: string;
    timestamp: _Timestamp;
    category: _BillCategory;
    amount: bigint;
}): {
    id: BillId;
    status: BillStatus;
    userId: UserId;
    billerId: string;
    timestamp: Timestamp;
    category: BillCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BillStatus_n56(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        billerId: value.billerId,
        timestamp: value.timestamp,
        category: from_candid_BillCategory_n31(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransferId;
    status: _TransferStatus;
    note: string;
    timestamp: _Timestamp;
    amount: bigint;
    recipientId: _UserId;
    senderId: _UserId;
}): {
    id: TransferId;
    status: TransferStatus;
    note: string;
    timestamp: Timestamp;
    amount: bigint;
    recipientId: UserId;
    senderId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_TransferStatus_n63(_uploadFile, _downloadFile, value.status),
        note: value.note,
        timestamp: value.timestamp,
        amount: value.amount,
        recipientId: value.recipientId,
        senderId: value.senderId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlanId;
    validity: bigint;
    operator: _Operator;
    name: string;
    description: string;
    isActive: boolean;
    price: bigint;
    planType: _PlanType;
}): {
    id: PlanId;
    validity: bigint;
    operator: Operator;
    name: string;
    description: string;
    isActive: boolean;
    price: bigint;
    planType: PlanType;
} {
    return {
        id: value.id,
        validity: value.validity,
        operator: from_candid_Operator_n9(_uploadFile, _downloadFile, value.operator),
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        price: value.price,
        planType: from_candid_PlanType_n11(_uploadFile, _downloadFile, value.planType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vi: null;
} | {
    jio: null;
} | {
    bsnl: null;
} | {
    airtel: null;
} | {
    tataSky: null;
} | {
    dishTV: null;
}): Operator {
    return "vi" in value ? Operator.vi : "jio" in value ? Operator.jio : "bsnl" in value ? Operator.bsnl : "airtel" in value ? Operator.airtel : "tataSky" in value ? Operator.tataSky : "dishTV" in value ? Operator.dishTV : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dth: null;
} | {
    mobile: null;
}): PlanType {
    return "dth" in value ? PlanType.dth : "mobile" in value ? PlanType.mobile : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    success: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "success" in value ? TransactionStatus.success : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topUp: {
    };
} | {
    bill: {
        billerId: string;
        category: _BillCategory;
    };
} | {
    deposit: {
        durationDays: bigint;
        interestRate: bigint;
    };
} | {
    recharge: {
        planId: bigint;
        operator: _Operator;
        targetNumber: string;
    };
} | {
    transfer: {
        note: string;
        recipientId: _UserId;
    };
}): {
    __kind__: "topUp";
    topUp: {
    };
} | {
    __kind__: "bill";
    bill: {
        billerId: string;
        category: BillCategory;
    };
} | {
    __kind__: "deposit";
    deposit: {
        durationDays: bigint;
        interestRate: bigint;
    };
} | {
    __kind__: "recharge";
    recharge: {
        planId: bigint;
        operator: Operator;
        targetNumber: string;
    };
} | {
    __kind__: "transfer";
    transfer: {
        note: string;
        recipientId: UserId;
    };
} {
    return "topUp" in value ? {
        __kind__: "topUp",
        topUp: value.topUp
    } : "bill" in value ? {
        __kind__: "bill",
        bill: from_candid_record_n30(_uploadFile, _downloadFile, value.bill)
    } : "deposit" in value ? {
        __kind__: "deposit",
        deposit: value.deposit
    } : "recharge" in value ? {
        __kind__: "recharge",
        recharge: from_candid_record_n33(_uploadFile, _downloadFile, value.recharge)
    } : "transfer" in value ? {
        __kind__: "transfer",
        transfer: value.transfer
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gas: null;
} | {
    internet: null;
} | {
    electricity: null;
} | {
    water: null;
}): BillCategory {
    return "gas" in value ? BillCategory.gas : "internet" in value ? BillCategory.internet : "electricity" in value ? BillCategory.electricity : "water" in value ? BillCategory.water : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topUp: null;
} | {
    bill: null;
} | {
    deposit: null;
} | {
    recharge: null;
} | {
    transfer: null;
}): TxType {
    return "topUp" in value ? TxType.topUp : "bill" in value ? TxType.bill : "deposit" in value ? TxType.deposit : "recharge" in value ? TxType.recharge : "transfer" in value ? TxType.transfer : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DepositRecord;
} | {
    err: string;
} | {
    insufficientBalance: null;
} | {
    userNotFound: null;
} | {
    invalidDuration: null;
}): {
    __kind__: "ok";
    ok: DepositRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
} | {
    __kind__: "invalidDuration";
    invalidDuration: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DepositRecord_n46(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "insufficientBalance" in value ? {
        __kind__: "insufficientBalance",
        insufficientBalance: value.insufficientBalance
    } : "userNotFound" in value ? {
        __kind__: "userNotFound",
        userNotFound: value.userNotFound
    } : "invalidDuration" in value ? {
        __kind__: "invalidDuration",
        invalidDuration: value.invalidDuration
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    matured: null;
} | {
    withdrawn: null;
}): DepositStatus {
    return "active" in value ? DepositStatus.active : "matured" in value ? DepositStatus.matured : "withdrawn" in value ? DepositStatus.withdrawn : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: null;
} | {
    failed: null;
}): BillStatus {
    return "success" in value ? BillStatus.success : "failed" in value ? BillStatus.failed : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Transaction;
} | {
    err: string;
} | {
    insufficientBalance: null;
} | {
    planNotFound: null;
} | {
    planInactive: null;
}): {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "planNotFound";
    planNotFound: null;
} | {
    __kind__: "planInactive";
    planInactive: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Transaction_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "insufficientBalance" in value ? {
        __kind__: "insufficientBalance",
        insufficientBalance: value.insufficientBalance
    } : "planNotFound" in value ? {
        __kind__: "planNotFound",
        planNotFound: value.planNotFound
    } : "planInactive" in value ? {
        __kind__: "planInactive",
        planInactive: value.planInactive
    } : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DepositRecord;
} | {
    err: string;
} | {
    alreadyProcessed: null;
} | {
    notYetMatured: null;
} | {
    depositNotFound: null;
}): {
    __kind__: "ok";
    ok: DepositRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "alreadyProcessed";
    alreadyProcessed: null;
} | {
    __kind__: "notYetMatured";
    notYetMatured: null;
} | {
    __kind__: "depositNotFound";
    depositNotFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DepositRecord_n46(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "alreadyProcessed" in value ? {
        __kind__: "alreadyProcessed",
        alreadyProcessed: value.alreadyProcessed
    } : "notYetMatured" in value ? {
        __kind__: "notYetMatured",
        notYetMatured: value.notYetMatured
    } : "depositNotFound" in value ? {
        __kind__: "depositNotFound",
        depositNotFound: value.depositNotFound
    } : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BillRecord;
} | {
    err: string;
} | {
    insufficientBalance: null;
} | {
    userNotFound: null;
}): {
    __kind__: "ok";
    ok: BillRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BillRecord_n54(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "insufficientBalance" in value ? {
        __kind__: "insufficientBalance",
        insufficientBalance: value.insufficientBalance
    } : "userNotFound" in value ? {
        __kind__: "userNotFound",
        userNotFound: value.userNotFound
    } : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TransferRecord;
} | {
    err: string;
} | {
    insufficientBalance: null;
} | {
    recipientNotFound: null;
} | {
    senderNotFound: null;
}): {
    __kind__: "ok";
    ok: TransferRecord;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "insufficientBalance";
    insufficientBalance: null;
} | {
    __kind__: "recipientNotFound";
    recipientNotFound: null;
} | {
    __kind__: "senderNotFound";
    senderNotFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TransferRecord_n61(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "insufficientBalance" in value ? {
        __kind__: "insufficientBalance",
        insufficientBalance: value.insufficientBalance
    } : "recipientNotFound" in value ? {
        __kind__: "recipientNotFound",
        recipientNotFound: value.recipientNotFound
    } : "senderNotFound" in value ? {
        __kind__: "senderNotFound",
        senderNotFound: value.senderNotFound
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TxRecord>): Array<TxRecord> {
    return value.map((x)=>from_candid_TxRecord_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OperatorRevenue>): Array<OperatorRevenue> {
    return value.map((x)=>from_candid_OperatorRevenue_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlanView>): Array<PlanView> {
    return value.map((x)=>from_candid_PlanView_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BillRecord>): Array<BillRecord> {
    return value.map((x)=>from_candid_BillRecord_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositRecord>): Array<DepositRecord> {
    return value.map((x)=>from_candid_DepositRecord_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransferRecord>): Array<TransferRecord> {
    return value.map((x)=>from_candid_TransferRecord_n61(_uploadFile, _downloadFile, x));
}
function to_candid_AppSettingsUpdate_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppSettingsUpdate): _AppSettingsUpdate {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_BillCategory_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillCategory): _BillCategory {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePlanArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePlanArgs): _CreatePlanArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Operator_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Operator): _Operator {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PlanType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TxFilter_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxFilter): _TxFilter {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_TxStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxStatus): _TxStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_TxType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): _TxType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType | null): [] | [_PlanType] {
    return value === null ? candid_none() : candid_some(to_candid_PlanType_n5(_uploadFile, _downloadFile, value));
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: TxStatus;
    dateTo?: Timestamp;
    operator?: Operator;
    txType?: TxType;
    dateFrom?: Timestamp;
}): {
    status: [] | [_TxStatus];
    dateTo: [] | [_Timestamp];
    operator: [] | [_Operator];
    txType: [] | [_TxType];
    dateFrom: [] | [_Timestamp];
} {
    return {
        status: value.status ? candid_some(to_candid_TxStatus_n20(_uploadFile, _downloadFile, value.status)) : candid_none(),
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        operator: value.operator ? candid_some(to_candid_Operator_n3(_uploadFile, _downloadFile, value.operator)) : candid_none(),
        txType: value.txType ? candid_some(to_candid_TxType_n22(_uploadFile, _downloadFile, value.txType)) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    validity: bigint;
    operator: Operator;
    name: string;
    description: string;
    price: bigint;
    planType: PlanType;
}): {
    validity: bigint;
    operator: _Operator;
    name: string;
    description: string;
    price: bigint;
    planType: _PlanType;
} {
    return {
        validity: value.validity,
        operator: to_candid_Operator_n3(_uploadFile, _downloadFile, value.operator),
        name: value.name,
        description: value.description,
        price: value.price,
        planType: to_candid_PlanType_n5(_uploadFile, _downloadFile, value.planType)
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    enableMobileRecharge?: boolean;
    enableDthRecharge?: boolean;
    appDisplayName?: string;
    commissionRateBps?: bigint;
    enableDigitalDeposit?: boolean;
    enableBillPayment?: boolean;
    enableMoneyTransfer?: boolean;
}): {
    enableMobileRecharge: [] | [boolean];
    enableDthRecharge: [] | [boolean];
    appDisplayName: [] | [string];
    commissionRateBps: [] | [bigint];
    enableDigitalDeposit: [] | [boolean];
    enableBillPayment: [] | [boolean];
    enableMoneyTransfer: [] | [boolean];
} {
    return {
        enableMobileRecharge: value.enableMobileRecharge ? candid_some(value.enableMobileRecharge) : candid_none(),
        enableDthRecharge: value.enableDthRecharge ? candid_some(value.enableDthRecharge) : candid_none(),
        appDisplayName: value.appDisplayName ? candid_some(value.appDisplayName) : candid_none(),
        commissionRateBps: value.commissionRateBps ? candid_some(value.commissionRateBps) : candid_none(),
        enableDigitalDeposit: value.enableDigitalDeposit ? candid_some(value.enableDigitalDeposit) : candid_none(),
        enableBillPayment: value.enableBillPayment ? candid_some(value.enableBillPayment) : candid_none(),
        enableMoneyTransfer: value.enableMoneyTransfer ? candid_some(value.enableMoneyTransfer) : candid_none()
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionStatus): {
    pending: null;
} | {
    success: null;
} | {
    failed: null;
} {
    return value == TransactionStatus.pending ? {
        pending: null
    } : value == TransactionStatus.success ? {
        success: null
    } : value == TransactionStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): {
    topUp: null;
} | {
    bill: null;
} | {
    deposit: null;
} | {
    recharge: null;
} | {
    transfer: null;
} {
    return value == TxType.topUp ? {
        topUp: null
    } : value == TxType.bill ? {
        bill: null
    } : value == TxType.deposit ? {
        deposit: null
    } : value == TxType.recharge ? {
        recharge: null
    } : value == TxType.transfer ? {
        transfer: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Operator): {
    vi: null;
} | {
    jio: null;
} | {
    bsnl: null;
} | {
    airtel: null;
} | {
    tataSky: null;
} | {
    dishTV: null;
} {
    return value == Operator.vi ? {
        vi: null
    } : value == Operator.jio ? {
        jio: null
    } : value == Operator.bsnl ? {
        bsnl: null
    } : value == Operator.airtel ? {
        airtel: null
    } : value == Operator.tataSky ? {
        tataSky: null
    } : value == Operator.dishTV ? {
        dishTV: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): {
    dth: null;
} | {
    mobile: null;
} {
    return value == PlanType.dth ? {
        dth: null
    } : value == PlanType.mobile ? {
        mobile: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BillCategory): {
    gas: null;
} | {
    internet: null;
} | {
    electricity: null;
} | {
    water: null;
} {
    return value == BillCategory.gas ? {
        gas: null
    } : value == BillCategory.internet ? {
        internet: null
    } : value == BillCategory.electricity ? {
        electricity: null
    } : value == BillCategory.water ? {
        water: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
